# Generated by Django 4.0.2 on 2022-02-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=7)),
                ('hex', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('style', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imageurl', models.CharField(max_length=150)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collection')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.color')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.type')),
            ],
            options={
                'db_table': 'weapon',
            },
        ),
    ]
