# Generated by Django 4.0.2 on 2022-02-04 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_collection_name_alter_color_hex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imageurl', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=5)),
                ('weapon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weapon')),
            ],
            options={
                'db_table': 'description',
            },
        ),
        migrations.CreateModel(
            name='Case_has_weapon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.case')),
                ('weapon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weapon')),
            ],
            options={
                'db_table': 'case_has_weapon',
                'unique_together': {('case_id', 'weapon_id')},
            },
        ),
    ]
