# Generated by Django 4.0.2 on 2022-02-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_description_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('de', 'German')], max_length=2),
        ),
    ]
