# Generated by Django 4.0.2 on 2022-02-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_weapon_statrak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='statrak',
            field=models.BooleanField(),
        ),
    ]
