# Generated by Django 4.0.2 on 2022-02-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_case_is_special_alter_weapon_statrak'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='rarity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
