# Generated by Django 4.0.2 on 2022-02-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_weapon_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='case',
            name='link_name',
            field=models.CharField(default='default', max_length=45),
            preserve_default=False,
        ),
    ]
