# Generated by Django 4.0.2 on 2022-02-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_case_is_available_case_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_has_weapon',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
