# Generated by Django 4.0.2 on 2022-02-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_case_has_weapon_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='rarity',
        ),
        migrations.AddField(
            model_name='case_has_weapon',
            name='rarity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
