# Generated by Django 4.0.2 on 2022-03-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.action_type'),
        ),
    ]
