# Generated by Django 4.0.2 on 2022-03-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_action_type_alter_action_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='action',
            table='action',
        ),
        migrations.AlterModelTable(
            name='action_type',
            table='action_type',
        ),
    ]
