# Generated by Django 4.0.2 on 2022-03-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_action_table_alter_action_type_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='object_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
