# Generated by Django 4.0.2 on 2022-03-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_action_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='object_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
